config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "cocktails#index"
  resources :cocktails, only: [ :show, :new, :create, :index ] do
    resources :doses, only: [ :new, :create, :destroy]
  end
  # resources :ingredients, only: [ :index, :show, :new, :create ]
  # resources :doses, only: [ :destroy ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail_id, presence: true
  validates :ingredient_id, presence: true, uniqueness: { scope: :cocktail_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]

  def index
    @cocktails = Cocktail.all
  end

  def show
  @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
   before_action :set_cocktail, only: [:new, :create, :destroy]
   # before_action :set_ingredient, only: [:create]

  # def index
  #   @cocktails = Cocktail.all
  # end

  def show

  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    # @ingredient = Ingredient.find(params[:ingredient_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # @dose.ingredient = @ingredient
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    dose = Dose.find(params[:id])
    cocktail = dose.cocktail
    dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    # @ingredient = Ingredient.find(params[:ingredient_id])
  end


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [ :show ]

  def index
    @ingredient = Ingredient.all
  end

  def show

  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_form.html.erb
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/cocktails/index.html.erb
<h1>All cocktails</h1>
  <ul>
    <% @cocktails.each do |cocktail| %>
      <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
    <% end %>
  </ul>
  <%= link_to "Add a cocktail", new_cocktail_path %>
  <%= cl_image_tag('jucpbzbp03tb0zipp2eu',width: 400, height: 300, crop: :fill) %>

app/views/cocktails/new.html.erb
<h1>Add a new cocktail</h1>

  <%= render "form" %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>

  <ul><% @cocktail.doses.each do |dose| %>
  <li><%= dose.description %> - <%= dose.ingredient.name %></li>
   <%= link_to "Delete a dose", cocktail_dose_path(@cocktail, dose), method: :delete, data: { confirm: "Are you sure?" } %>
  </ul>
  <% end %>
  <br>
  <%= link_to "Back to all cocktails", cocktails_path %>
  <br>
  <%= link_to "Add a dose to your cocktail", new_cocktail_dose_path(@cocktail) %>
  <br>

app/views/doses/_form.html.erb
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>

app/views/doses/new.html.erb
<h1>Add a new dose</h1>

  <%= render "form" %>
  <%= link_to "Back to your cocktail", cocktail_path(@cocktail) %>

app/views/ingredients/index.html.erb
<h1>All ingredients</h1>

  <ul>
    <% @ingredient.each do |ingredient| %>
      <li><%= ingredient.name %></li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  </head>

  <body>
    <%= yield %>
      <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
      <%= javascript_pack_tag "application" %>
  </body>
</html>